## sls deploy  --stage dev --region us-east-1  --version --verbose

###### DON'T CHANGE THIS #######
org: ${self:custom.basic.org}
app: ${self:custom.basic.app}
###### DON'T CHANGE THIS #######

service: ${self:custom.services.TestServiceApi.name}

# configValidationMode: warn
frameworkVersion: "3"

## Here you can change your provider
provider:
  name: "aws"
  profile: ${self:custom.common.profiles.${sls:stage}}
  memorySize: 256
  timeout: 10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}

## Here you can change your custom variables
custom:
  common: ${file('../serverless-common.yml'):custom.common}
  basic: ${file('../serverless-common.yml'):custom.basic}
  services: ${file('../serverless-common.yml'):custom.services}

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-offline

package:
  individually: true
  patterns:
    - "!**"

functions: ${file(./serverless-dynamic-function.js)} # auto discover the functions

# you can add serverless framework output here
outputs:
  app_name: ${self:app}
  service_name: ${self:service}
  stage: ${self:provider.stage}
  region: ${self:provider.region}

# you can add CloudFormation resource templates here
resources:
  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
