## sls deploy  --stage dev --region us-east-1  --version --verbose

org: ${self:custom.basic.org}
app: ${self:custom.basic.app}

service: ${self:custom.services.TestServiceApi.name}

# configValidationMode: warn
frameworkVersion: "3"

## Here you can change your provider
provider:
  name: "aws"
  profile: ${self:custom.common.profiles.${sls:stage}}
  memorySize: 256
  timeout: 10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}


## Here you can change your custom variables
custom:
  common:
    profiles:
      dev: account-profile-dev
      prod: account-profile-prod
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    
  basic: 
    org: serverless_framework_org
    app: serverless_framework_app 
    
  services:
    TestServiceApi:
      name: test-service-api
      description: "A test service for rest api" 


plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-offline


package:
  individually: true
  patterns:
    - "!**"
    
functions:
  ${file(./serverless-dynamic-function.js)} # auto discover the functions

# you can add serverless framework output here
outputs:
  app_name: ${self:app}
  service_name: ${self:service}
  stage: ${self:provider.stage}
  region: ${self:provider.region}

# you can add CloudFormation resource templates here
resources:
  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
